[package]
name = "Game"
version = "0.1.0"
authors = ["Madara <guesswecan@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.32.1"

[[example]]
name = "01_window"